### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by bless1003** [debo1994/MyTimes#1]
Hi! Some suggestions 

Search bar( q endpoint search query within newsapi)  and more sources which are available in v2 categories like health - medical, science and nature.

make Google India as default.

**Comment by bless1003** [comment]
Please do this if you find some time

Published dates also be there in headlines.

**Comment by debajyotibasak** [comment]
As you requested Search bar is added. and Google India is made default. Added Science Category too. Publish dates would be available in the next update.
